services:

  backend:
    build: ../backend
    container_name: medical_backend  
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ../backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    env_file:                     
      - ../backend/.env.docker

  db:
    image: postgres:15
    container_name: medical_postgres_db  
    environment:
      POSTGRES_DB: medical_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"

  redis:
    image: redis:7
    container_name: medical_redis   
    ports:
      - "6379:6379"

  worker:
    build: ../backend
    container_name: medical_celery_worker   
    command: celery -A medical_dashboard worker -l info -n worker@%h
    volumes:
      - ../backend:/app
    depends_on:
      - backend
      - redis
    env_file:                     
      - ../backend/.env.docker
